defaults: &defaults
  host: localhost
#  slaves:
#    - host: slave.local
#      port: 27018
#    - host: slave2.local
#      port: 27019

development:
  <<: *defaults
  databases: store_development

test:
  <<: *defaults
  databases: store_test

production:
  host: <%= ENV['MONGOID_HOST']%>
  port: <%= ENV['MONGOID_PORT']%>
  username: <%= ENV['MONGOID_USERNAME']%>
  passowrd: <%= ENV['MONGOID_PASSWORD']%>
  database: <%= ENV['MONGOID_DATABASE']%>